default_platform(:mac)
#xcodes(version: "15.2.0") 

platform :mac do
    desc "Build, and create a DMG file"

    lane :release do
      prepare_signing
      build
      dmg(path: "builds", output_path: "./release/capture-wolf.dmg")
    end

    lane :test do
      build
      dmg(path: "builds", output_path: "./release/capture-wolf.dmg")
    end

    desc "Build the IOS Application"
    lane :build do
      gym(
        clean: true,
        export_method: "mac-application",
        output_directory: "./builds"
      )
    end


    desc "Installs signing certificate in the keychain"
    lane :prepare_signing do |options|

      keychain_name = "signing"
      keychain_password = "temp"

      delete_keychain(
        name: keychain_name
      ) if File.exist? File.expand_path("~/Library/Keychains/#{keychain_name}-db")

      create_keychain(
        name: keychain_name,
        password: keychain_password,
        default_keychain: true,
        unlock: true,
        timeout: 3600
      )

      import_certificate(
        certificate_path: ENV["SIGNING_CERT_FILE_PATH"],
        certificate_password: ENV["SIGNING_CERT_PASSWORD"],
        keychain_name: keychain_name,
        keychain_password: keychain_password
      )

      import_certificate(
        certificate_path: ENV["SIGNING_KEY_FILE_PATH"],
        keychain_name: keychain_name,
        keychain_password: keychain_password
      )
      
      delete_keychain(
        name: keychain_name
      )
    end
end