name: OSX

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-14

    defaults:
      run:
        working-directory: ${{ github.workspace }}/OSX
        
    steps:
      - name: Checkout files
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 21
      
      - name: "Setup git user"
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"
        
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      
      - name: List Xcode installations
        run: sudo ls -1 /Applications | grep "Xcode"
      
      - name: Select XCode version
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: '15.2.0'

      - name: Install dependencies
        run: bundle install
      
      - name: Decode signing certificate into a file
        env:
          CERTIFICATE_BASE64: ${{ secrets.SIGNING_CERT }}
        run: echo $CERTIFICATE_BASE64 | base64 --decode > signing-cert.cer
      
      - name: Decode signing key into a file
        env:
          KEY_BASE64: ${{ secrets.SIGNING_KEY }}
        run: echo $KEY_BASE64 | base64 --decode > signing-key.p12

      - uses: yanamura/ios-bump-version@v1
        with:
          version: 1.0.5

      - name: Deploy app
        run: bundle exec fastlane release
        env:
          SIGNING_CERT_PASSWORD:  ${{ secrets.SIGNING_CERT_PASSWORD}}
          SIGNING_CERT_FILE_PATH: signing-cert.cer
          SIGNING_KEY_FILE_PATH: signing-key.p12
 
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: ./OSX/release/
        
      - name: update
        run: |
          git add .
          git commit -m "bump version [skip ci]"
          git push origin HEAD


      
      