name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ./Windows/CaptureWolf.sln

    - name: Build
      run: dotnet build --configuration Release --no-restore ./Windows/CaptureWolf.Form/CaptureWolf.UI.csproj

    - name: Zip output
      run: |
        cd ./Windows/CaptureWolf.Form/bin/Release
        7z a output.zip ./*
      shell: pwsh

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: ./Windows/CaptureWolf.Form/bin/Release/output.zip

  build_installer:
    needs: build
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ./Windows/CaptureWolf.sln

    - name: Build Installer
      run: dotnet build --configuration Release --no-restore ./Windows/CaptureWolf.Installer/CaptureWolf.Installer.vdproj

    - name: Zip MSI
      run: |
        cd ./Windows/CaptureWolf.Installer/bin/Release
        7z a installer.zip ./*.msi
      shell: pwsh

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: installer
        path: ./Windows/CaptureWolf.Installer/bin/Release/installer.zip
