name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ./Windows/CaptureWolf.sln

    - name: Setup VS Dev Environment
      uses: seanmiddleditch/gha-setup-vsdevenv@v4

    - name: Build
      run: dotnet build --configuration Release --no-restore ./Windows/CaptureWolf.Form/CaptureWolf.UI.csproj

    - name: Build Installer
      run: devenv.com ./Windows/CaptureWolf.Installer/CaptureWolf.Installer.vdproj /build "Release|Any CPU"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: ./Windows/CaptureWolf.Form/bin/Release/

    - name: Upload Installer
      uses: actions/upload-artifact@v2
      with:
        name: installer
        path: ./Windows/CaptureWolf.Installer/Release/
